apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dataopener
  name: dataopener-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dataopener-production
      app.kubernetes.io/name: dataopener
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dataopener-production
        app.kubernetes.io/name: dataopener
    spec:
      containers:
        - image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
          name: dataopener
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
