apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataopener
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
          name: dataopener
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
