apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mutix
nameSuffix: "-production"
commonLabels:
  app: dataopener
  app.kubernetes.io/name: dataopener
  app.kubernetes.io/instance: dataopener-production
resources:
- deployment.yaml
- service.yaml