apiVersion: v1
kind: Service
metadata:
  name: dataopener
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  sessionAffinity: None
  type: NodePort
