apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: "{{ .Release.Name }}-port"
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
  sessionAffinity: None
  type: NodePort
